name: build-test
on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install packages
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
      - run: yarn --ignore-scripts
        shell: bash
      - name: Create local node and deploy
        run: |
          cp .env.github .env &&
          sudo yarn compile &&
          yarn hardhat node &
          sleep 2 &&
          yarn hardhat run scripts/deploy.ts --network localhost
      - name: tests
        run: yarn hardhat test
